### ISSUE TITLE
Building InfOS with MinGW64 on Windows

### ISSUE THREAD

**Issue by Vidminas** [tspink/infos#1]
Hi!

Out of interest (and since the university currently recommends self-isolation), I was trying to build InfOS locally on my Windows laptop.
I am using Windows 10 and MinGW64 8.1.0 (x86_64-8.1.0-posix-seh-rt_v6-rev0)
I could not manage to get it to build and I was not sure whether this is a bug with InfOS, MinGW or g++, any advice would be much appreciated.

Make in the infos root directory fails with:
```
$ make
  CXX      arch/x86/cpu.o
cc1plus.exe: error: code model kernel does not support PIC mode
```
I've looked into this and all information I could find says to compile with `-fno-pic` (or `-fno-PIC`). However, line 20 of the Makefile already has `export common-flags := -I$(inc-dir) -nostdinc -nostdlib -g -Wall -O3 -std=gnu++17 -fno-pic`.
It's as if the flag is just ignored - there is no difference if I remove it.
It seems like this has nothing to do with flag positionality either, as moving the flag in different places (including adding it inline to make targets) did not change anything at all.

**Comment by tspink** [comment]
I'm unable to diagnose, because I haven't got access to a Windows set up.
Could you try running 'make' with 'q=':

# make q=

That's q equal to blank, which should then show the commands make is trying
to execute. Then, look at the command to verify the flag is present, and
also try to manually execute the command, to see if it works from the
command-line, and not from the Makefile.

Tom.

**Comment by Vidminas** [comment]
Hi Tom,
Thanks for the tip!

With `make q=` the resulting output does show that it includes the `-fno-pic` flag:
```
g++ -M -MT C:/Users/Vidminas/GitHub/os-coursework/infos/arch/x86/cpu.o -o C:/Users/Vidminas/GitHub/os-coursework/infos/arch/x86/cpu.d -IC:/Users/Vidminas/GitHub/os-coursework/infos/include -nostdinc -nostdlib -g -Wall -O3 -std=gnu++17 -fno-pic -mcmodel=kernel -ffreestanding -fno-builtin -fno-omit-frame-pointer -fno-rtti -fno-exceptions -fno-stack-protector -fno-delete-null-pointer-checks -mno-red-zone -mno-mmx -mno-sse -mno-sse2 -mno-sse3 -mno-ssse3 -mno-sse4.1 -mno-sse4.2 -mno-sse4 -mno-avx -mno-aes -mno-sse4a -mno-fma4 C:/Users/Vidminas/GitHub/os-coursework/infos/arch/x86/cpu.cpp
cc1plus.exe: error: code model kernel does not support PIC mode
```
Running the same command manually also produces the exact same error.
I guess that must be a MinGW64 issue then.

On the bright side, I found that building using g++ on WSL works flawlessly, and I can then run QEMU on Windows to load the system image built with WSL. InfOS runs even better than on DICE like this =)
